In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("C:/Users/Z003N71U/Downloads/Training/stocks.small.csv")

In [7]:
df.head()

,date,open,high,low,close,volume,adjclose,symbol
0,2000-07-18,144.81250,144.828125,141.437500,143.0000,50683600.0,50.155473,INTC
1,2000-07-20,32.93751,34.250010,32.812500,33.7500,3288300.0,8.789734,BEN
2,2000-07-24,64.25000,67.312477,64.187523,64.7500,948800.0,7.689567,APH
3,2000-07-26,21.87500,22.125000,20.937500,20.9375,1464300.0,15.618320,SHW
4,2000-07-26,42.00000,42.312481,41.625000,41.8750,1397600.0,9.402721,STJ

In [9]:
# 1. Find the total number of records
len(df)

1846

In [18]:
#2. Find the number of records by stock symbol
df.groupby(df.symbol).symbol.count()

symbol
A        2
AA       5
AAL      1
AAP      5
AAPL     3
ABC      2
ABT      6
ACN      2
ADBE     2
ADI      6
ADM      6
ADP      1
ADS      3
ADSK     4
AEE      4
AEP      3
AES      7
AET      5
AFL      3
AGN      5
AIG      5
AIV      3
AIZ      4
AKAM     4
ALB      5
ALK      7
ALL      3
ALLE     1
ALXN     1
AMAT     3
        ..
VRTX     2
VTR      6
VZ       7
WAT      7
WBA      4
WDC      7
WEC      2
WFC      7
WFM      3
WHR      5
WM       6
WMB      5
WMT      8
WRK      1
WU       2
WY       3
WYN      5
WYNN     6
XEC      3
XEL      2
XL       3
XLNX     6
XOM      3
XRAY     5
XRX      1
XYL      2
YHOO     5
YUM      6
ZBH     11
ZION     2
Name: symbol, Length: 471, dtype: int64

In [20]:
# 3. Find avg volume per stock
import numpy as np
df.groupby("symbol").agg({"volume": np.mean})

              volume
symbol
A       4.817800e+06
AA      2.177992e+07
AAL     2.598900e+06
AAP     1.274240e+06
AAPL    1.663662e+08
ABC     1.828200e+06
ABT     1.314022e+07
ACN     3.198850e+06
ADBE    4.725700e+06
ADI     2.909117e+06
ADM     4.904967e+06
ADP     1.074600e+06
ADS     7.642000e+05
ADSK    3.393800e+06
AEE     9.350750e+05
AEP     1.866267e+06
AES     4.188586e+06
AET     5.830220e+06
AFL     1.896633e+06
AGN     1.079380e+06
AIG     3.441720e+06
AIV     8.612000e+05
AIZ     1.017925e+06
AKAM    3.719875e+06
ALB     5.175200e+05
ALK     2.896700e+06
ALL     2.904833e+06
ALLE    4.711000e+05
ALXN    1.463200e+06
AMAT    2.433693e+07
...              ...
VRTX    1.641950e+06
VTR     1.545000e+06
VZ      1.336177e+07
WAT     1.269814e+06
WBA     4.418425e+06
WDC     3.105371e+06
WEC     6.506000e+05
WFC     2.181037e+07
WFM     4.218267e+06
WHR     9.932800e+05
WM      2.534883e+06
WMB     7.113100e+06
WMT     1.216526e+07
WRK     2.397300e+06
WU      4.839500e+06
WY      1.098333e+06
WYN     1.353540e+06
WYNN    3.704533e+06
XEC     1.375533e+06
XEL     1.071800e+06
XL      7.067333e+05
XLNX    6.288650e+06
XOM     2.776827e+07
XRAY    1.117300e+06
XRX     3.019200e+06
XYL     7.209500e+05
YHOO    2.308414e+07
YUM     1.796917e+06
ZBH     1.616664e+06
ZION    3.220250e+06

[471 rows x 1 columns]

In [33]:
#4. Find Symbol and date that has highest intra day pct chnage in price
import math
def find_intraDay(row):
    return math.fabs(row["close"] - row["open"]) / row["open"]
    
df["IntraDayPCTChange"] = df.apply(find_intraDay, axis = 1)
df.groupby("symbol").agg({"IntraDayPCTChange": np.max}).sort_values("IntraDayPCTChange", ascending = False)

        IntraDayPCTChange
symbol
RHT              0.121094
ALK              0.116162
TGNA             0.115132
BIIB             0.109220
CCL              0.105158
ETFC             0.100000
RHI              0.096698
XLNX             0.091743
FLIR             0.090903
LM               0.090523
LLTC             0.088764
MU               0.087774
ENDP             0.083934
HUM              0.081818
KLAC             0.081204
FMC              0.077778
HON              0.077626
MDT              0.074787
IP               0.071781
CA               0.069859
WMB              0.069840
IFF              0.069757
FLS              0.069530
JWN              0.068880
AXP              0.068376
AYI              0.068244
AET              0.067491
HOG              0.064857
AZO              0.063972
SRCL             0.063819
...                   ...
EW               0.004985
VRSK             0.004921
GIS              0.004840
AEP              0.004835
TDG              0.004593
UHS              0.004580
BAC              0.004359
FB               0.004294
SEE              0.004254
TXN              0.004217
KMX              0.004000
LKQ              0.003928
MAS              0.003771
MDLZ             0.003717
PFE              0.003611
OMC              0.003531
UDR              0.003183
DLTR             0.003126
SNI              0.002914
DNB              0.002783
COST             0.002743
KEY              0.002662
CBG              0.002597
ADP              0.002479
FBHS             0.002050
HBAN             0.002022
VFC              0.001840
PM               0.001360
LVLT             0.000367
ALLE             0.000313

[471 rows x 1 columns]

In [34]:
# 5. find the number of unique symbol
len(df.groupby(df.symbol))

471